name       : power-profiles-daemon
version    : 0.9.0
release    : 1
source     :
    - https://gitlab.freedesktop.org/hadess/power-profiles-daemon/-/archive/0.9.0/power-profiles-daemon-0.9.0.tar.bz2 : 67278728af6661b805dcf8dcaf96b9c89ecde928147dc4dca45f82e273ba3b80
license    : GPL-3.0-or-later
component  : programming.library
summary    : Makes power profiles handling available over D-Bus.
description: |
    Makes power profiles handling available over D-Bus.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(upower-glib)
setup      : |
    %meson_configure --sysconfdir=/usr/share
build      : |
    %ninja_build
install    : |
    %ninja_install
